# Generated by Django 4.2.2 on 2023-06-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='earned',
            field=models.IntegerField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='sgpa',
            field=models.IntegerField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='total',
            field=models.IntegerField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default='1', max_length=2),
        ),
    ]
